#ifndef _RESOURCES_HPP_
#define _RESOURCES_HPP_

#define ID_ADDON_INFO								32000

#define ID_MENU_STRINGS_FORMWORKS					32001
#define ID_MENU_PROMPT_STRINGS_FORMWORKS			32002
#define ID_MENU_STRINGS_LAYER_TOOLS					32003
#define ID_MENU_PROMPT_STRINGS_LAYER_TOOLS			32004
#define ID_MENU_STRINGS_EXPORTING					32005
#define ID_MENU_PROMPT_STRINGS_EXPORTING			32006
#define ID_MENU_STRINGS_SEMIAUTO_ARRANGE			32007
#define ID_MENU_PROMPT_STRINGS_SEMIAUTO_ARRANGE		32008
#define ID_MENU_STRINGS_FACILITIES					32009
#define ID_MENU_PROMPT_STRINGS_FACILITIES			32010

#define ID_MENU_ICON			32000

#endif //_RESOURCES_HPP_
